language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
before_deploy: cp ./tools/onesignal-sdk/* ./dist/apps/main/
env:
  global:
    secure: DgTo6WtrCz/MI1AHXl/a4gEt7ErAolEUuQ50ZnEqNGOLbfiYLoIv+/n4n8SVkx3q7nng2CD+/tzMcok9bQV0fh9HbFNfdWi8+PYWR2OzzT/HgoOES0RMiTJP4k9ngxVqM4WaXwhxupEEjetaYY7JiODd6Wx/sQQ3gLStTg7aGDrP3CoQgSF5+m6AQm1SlgfEIMcWzR4hP3gt7bp9fKPPCMtZqQQ/hvrMtAHi0hiqY+fo2+N40SPAkRR7pqZeVuo6ekfbsADfnbq9qDlmM8SIVO49h5tdbTnycLKNbinfkXHfh/EgGD9UEnMh46YU6qxEOE/Y6x2YnhGBd9REhx5+/qIBvtrXd3o0CXu/lKJmwQxxqmtxHpXfScKQcYXaxiZDwV4vG6PzCwmiq03pQJZ0T7kJC8Wc3UkO7UlXHeSg2yRE9E5c9wHm4uw8tmZtlpTSllF4WWYf7MjVp0QMF63XXpA/W1mwDwjZ/Y1CikGvKGCmT9j2nZ4CItBa55keIEp+yUdNK85m7ep+qd8uXi2lc8VQmUPi2ocC1njx8RWw4tkXoLdM/LnF6Ew6Nk8TfQFnswMbOiFidk0dIivnFop962fGvubIkKp6n/BLtB7XD19UC3EYoPtDdBe21N1Aq9a5Q05j9+YvBAyG2+4vjk4QkRZcRVCjnBe+gFzyaO1yILI=
